import { DraftPlayer } from "./draftEngine";

export interface RankedPlayer extends DraftPlayer {
  adp: number;
  consensusRank: number;
  tier: number;
  vbd?: number;
  vols?: number;
  fpVorp?: number;
  vbdRank?: number;
}

export const MASTER_PLAYER_DATABASE: RankedPlayer[] = [
  {
    id: "p1",
    name: "Ja'Marr Chase",
    pos: "WR",
    team: "CIN",
    bye: 6,
    projectedPoints: 350,
    consensusRank: 1,
    adp: 1.0,
    tier: 1,
    sos: 4,
    vbd: 346,
    vols: 141,
    fpVorp: 205,
    vbdRank: 7,
  },
  {
    id: "p2",
    name: "Jahmyr Gibbs",
    pos: "RB",
    team: "DET",
    bye: 6,
    projectedPoints: 349,
    consensusRank: 2,
    adp: 3.0,
    tier: 1,
    sos: 5,
    vbd: 487,
    vols: 197,
    fpVorp: 290,
    vbdRank: 1,
  },
  {
    id: "p3",
    name: "Puka Nacua",
    pos: "WR",
    team: "LAR",
    bye: 11,
    projectedPoints: 348,
    consensusRank: 3,
    adp: 2.0,
    tier: 1,
    sos: 1,
    vbd: 346,
    vols: 141,
    fpVorp: 205,
    vbdRank: 6,
  },
  {
    id: "p4",
    name: "Bijan Robinson",
    pos: "RB",
    team: "ATL",
    bye: 11,
    projectedPoints: 348,
    consensusRank: 4,
    adp: 6.0,
    tier: 1,
    sos: 2,
    vbd: 453,
    vols: 180,
    fpVorp: 273,
    vbdRank: 2,
  },
  {
    id: "p5",
    name: "Jaxon Smith-Njigba",
    pos: "WR",
    team: "SEA",
    bye: 11,
    projectedPoints: 348,
    consensusRank: 5,
    adp: 4.0,
    tier: 1,
    sos: 3,
    vbd: 318,
    vols: 127,
    fpVorp: 191,
    vbdRank: 10,
  },
  {
    id: "p6",
    name: "Amon-Ra St. Brown",
    pos: "WR",
    team: "DET",
    bye: 6,
    projectedPoints: 347,
    consensusRank: 6,
    adp: 4.0,
    tier: 1,
    sos: 4,
    vbd: 338,
    vols: 137,
    fpVorp: 201,
    vbdRank: 8,
  },
  {
    id: "p7",
    name: "CeeDee Lamb",
    pos: "WR",
    team: "DAL",
    bye: 14,
    projectedPoints: 346,
    consensusRank: 7,
    adp: 4.0,
    tier: 2,
    sos: 2,
    vbd: 240,
    vols: 88,
    fpVorp: 152,
    vbdRank: 18,
  },
  {
    id: "p8",
    name: "Justin Jefferson",
    pos: "WR",
    team: "MIN",
    bye: 6,
    projectedPoints: 346,
    consensusRank: 8,
    adp: 4.0,
    tier: 2,
    sos: 5,
    vbd: 218,
    vols: 77,
    fpVorp: 141,
    vbdRank: 20,
  },
  {
    id: "p9",
    name: "Christian McCaffrey",
    pos: "RB",
    team: "SF",
    bye: 8,
    projectedPoints: 346,
    consensusRank: 9,
    adp: 13.0,
    tier: 2,
    sos: 2,
    injuryStatus: "Q",
    injuryDetails: "Calf/Achilles",
    vbd: 409,
    vols: 158,
    fpVorp: 251,
    vbdRank: 3,
  },
  {
    id: "p10",
    name: "Jonathan Taylor",
    pos: "RB",
    team: "IND",
    bye: 13,
    projectedPoints: 345,
    consensusRank: 10,
    adp: 13.0,
    tier: 2,
    sos: 4,
    vbd: 365,
    vols: 136,
    fpVorp: 229,
    vbdRank: 4,
  },
  {
    id: "p11",
    name: "Drake London",
    pos: "WR",
    team: "ATL",
    bye: 11,
    projectedPoints: 344,
    consensusRank: 11,
    adp: 2.0,
    tier: 2,
    sos: 3,
    vbd: 212,
    vols: 74,
    fpVorp: 138,
    vbdRank: 23,
  },
  {
    id: "p12",
    name: "A.J. Brown",
    pos: "WR",
    team: "NE",
    bye: 11,
    projectedPoints: 344,
    consensusRank: 12,
    adp: 6.0,
    tier: 3,
    sos: 2,
    vbd: 202,
    vols: 69,
    fpVorp: 133,
    vbdRank: 26,
  },
  {
    id: "p13",
    name: "James Cook III",
    pos: "RB",
    team: "BUF",
    bye: 7,
    projectedPoints: 344,
    consensusRank: 13,
    adp: 17.0,
    tier: 3,
    sos: 2,
    vbd: 289,
    vols: 98,
    fpVorp: 191,
    vbdRank: 13,
  },
  {
    id: "p14",
    name: "Nico Collins",
    pos: "WR",
    team: "HOU",
    bye: 8,
    projectedPoints: 343,
    consensusRank: 14,
    adp: 4.0,
    tier: 3,
    sos: 3,
    vbd: 170,
    vols: 53,
    fpVorp: 117,
    vbdRank: 34,
  },
  {
    id: "p15",
    name: "Chase Brown",
    pos: "RB",
    team: "CIN",
    bye: 6,
    projectedPoints: 342,
    consensusRank: 15,
    adp: 17.0,
    tier: 3,
    sos: 2,
    vbd: 319,
    vols: 113,
    fpVorp: 206,
    vbdRank: 9,
  },
  {
    id: "p16",
    name: "Chris Olave",
    pos: "WR",
    team: "NO",
    bye: 8,
    projectedPoints: 342,
    consensusRank: 16,
    adp: 6.0,
    tier: 3,
    sos: 3,
    vbd: 192,
    vols: 64,
    fpVorp: 128,
    vbdRank: 29,
  },
  {
    id: "p17",
    name: "Trey McBride",
    pos: "TE",
    team: "ARI",
    bye: 14,
    projectedPoints: 342,
    consensusRank: 17,
    adp: 9.0,
    tier: 3,
    sos: 2,
    vbd: 180,
    vols: 79,
    fpVorp: 101,
    vbdRank: 30,
  },
  {
    id: "p18",
    name: "George Pickens",
    pos: "WR",
    team: "DAL",
    bye: 14,
    projectedPoints: 341,
    consensusRank: 18,
    adp: 13.0,
    tier: 3,
    sos: 2,
    vbd: 174,
    vols: 55,
    fpVorp: 119,
    vbdRank: 31,
  },
  {
    id: "p19",
    name: "De'Von Achane",
    pos: "RB",
    team: "MIA",
    bye: 6,
    projectedPoints: 340,
    consensusRank: 19,
    adp: 27.0,
    tier: 3,
    sos: 3,
    injuryStatus: "Q",
    injuryDetails: "Ankle",
    vbd: 349,
    vols: 128,
    fpVorp: 221,
    vbdRank: 5,
  },
  {
    id: "p20",
    name: "Brock Bowers",
    pos: "TE",
    team: "LV",
    bye: 13,
    projectedPoints: 340,
    consensusRank: 20,
    adp: 18.0,
    tier: 3,
    sos: 3,
    vbd: 138,
    vols: 58,
    fpVorp: 80,
    vbdRank: 42,
  },
  {
    id: "p21",
    name: "DeVonta Smith",
    pos: "WR",
    team: "PHI",
    bye: 10,
    projectedPoints: 340,
    consensusRank: 21,
    adp: 10.0,
    tier: 3,
    sos: 4,
    vbd: 138,
    vols: 37,
    fpVorp: 101,
    vbdRank: 41,
  },
  {
    id: "p22",
    name: "Saquon Barkley",
    pos: "RB",
    team: "PHI",
    bye: 10,
    projectedPoints: 339,
    consensusRank: 22,
    adp: 30.0,
    tier: 3,
    sos: 4,
    vbd: 295,
    vols: 101,
    fpVorp: 194,
    vbdRank: 12,
  },
  {
    id: "p23",
    name: "Malik Nabers",
    pos: "WR",
    team: "NYG",
    bye: 8,
    projectedPoints: 338,
    consensusRank: 23,
    adp: 19.0,
    tier: 4,
    sos: 4,
    vbd: 88,
    vols: 12,
    fpVorp: 76,
    vbdRank: 56,
  },
  {
    id: "p24",
    name: "Kenneth Walker III",
    pos: "RB",
    team: "KC",
    bye: 5,
    projectedPoints: 338,
    consensusRank: 24,
    adp: 31.0,
    tier: 4,
    sos: 3,
    vbd: 261,
    vols: 84,
    fpVorp: 177,
    vbdRank: 14,
  },
  {
    id: "p25",
    name: "Omarion Hampton",
    pos: "RB",
    team: "LAC",
    bye: 7,
    projectedPoints: 338,
    consensusRank: 25,
    adp: 35.0,
    tier: 4,
    sos: 3,
    vbd: 243,
    vols: 75,
    fpVorp: 168,
    vbdRank: 16,
  },
  {
    id: "p26",
    name: "Josh Allen",
    pos: "QB",
    team: "BUF",
    bye: 7,
    projectedPoints: 337,
    consensusRank: 26,
    adp: 31.0,
    tier: 4,
    sos: 3,
    vbd: 138,
    vols: 64,
    fpVorp: 74,
    vbdRank: 40,
  },
  {
    id: "p27",
    name: "Rashee Rice",
    pos: "WR",
    team: "KC",
    bye: 5,
    projectedPoints: 336,
    consensusRank: 27,
    adp: 23.0,
    tier: 4,
    sos: 2,
    vbd: 218,
    vols: 77,
    fpVorp: 141,
    vbdRank: 19,
  },
  {
    id: "p28",
    name: "Ashton Jeanty",
    pos: "RB",
    team: "LV",
    bye: 13,
    projectedPoints: 336,
    consensusRank: 28,
    adp: 37.0,
    tier: 4,
    sos: 2,
    vbd: 255,
    vols: 81,
    fpVorp: 174,
    vbdRank: 15,
  },
  {
    id: "p29",
    name: "Zay Flowers",
    pos: "WR",
    team: "BAL",
    bye: 13,
    projectedPoints: 336,
    consensusRank: 29,
    adp: 23.0,
    tier: 4,
    sos: 4,
    injuryStatus: "Q",
    injuryDetails: "Lower Body",
    vbd: 174,
    vols: 55,
    fpVorp: 119,
    vbdRank: 32,
  },
  {
    id: "p30",
    name: "Garrett Wilson",
    pos: "WR",
    team: "NYJ",
    bye: 13,
    projectedPoints: 335,
    consensusRank: 30,
    adp: 21.0,
    tier: 4,
    sos: 4,
    vbd: 144,
    vols: 40,
    fpVorp: 104,
    vbdRank: 38,
  },
  {
    id: "p31",
    name: "Lamar Jackson",
    pos: "QB",
    team: "BAL",
    bye: 13,
    projectedPoints: 334,
    consensusRank: 31,
    adp: 26.0,
    tier: 4,
    sos: 3,
    vbd: 60,
    vols: 25,
    fpVorp: 35,
    vbdRank: 76,
  },
  {
    id: "p32",
    name: "Ladd McConkey",
    pos: "WR",
    team: "LAC",
    bye: 7,
    projectedPoints: 334,
    consensusRank: 32,
    adp: 21.0,
    tier: 4,
    sos: 2,
    vbd: 96,
    vols: 16,
    fpVorp: 80,
    vbdRank: 53,
  },
  {
    id: "p33",
    name: "Jaylen Waddle",
    pos: "WR",
    team: "DEN",
    bye: 10,
    projectedPoints: 334,
    consensusRank: 33,
    adp: 20.0,
    tier: 4,
    sos: 2,
    vbd: 88,
    vols: 12,
    fpVorp: 76,
    vbdRank: 57,
  },
  {
    id: "p34",
    name: "Tetairoa McMillan",
    pos: "WR",
    team: "CAR",
    bye: 5,
    projectedPoints: 333,
    consensusRank: 34,
    adp: 30.0,
    tier: 5,
    sos: 2,
    vbd: 114,
    vols: 25,
    fpVorp: 89,
    vbdRank: 46,
  },
  {
    id: "p35",
    name: "Tee Higgins",
    pos: "WR",
    team: "CIN",
    bye: 6,
    projectedPoints: 332,
    consensusRank: 35,
    adp: 29.0,
    tier: 5,
    sos: 4,
    vbd: 112,
    vols: 24,
    fpVorp: 88,
    vbdRank: 47,
  },
  {
    id: "p36",
    name: "Derrick Henry",
    pos: "RB",
    team: "BAL",
    bye: 13,
    projectedPoints: 332,
    consensusRank: 36,
    adp: 56.0,
    tier: 5,
    sos: 3,
    vbd: 303,
    vols: 105,
    fpVorp: 198,
    vbdRank: 11,
  },
  {
    id: "p37",
    name: "Drake Maye",
    pos: "QB",
    team: "NE",
    bye: 11,
    projectedPoints: 332,
    consensusRank: 37,
    adp: 22.0,
    tier: 5,
    sos: 2,
    vbd: 54,
    vols: 22,
    fpVorp: 32,
    vbdRank: 81,
  },
  {
    id: "p38",
    name: "Colston Loveland",
    pos: "TE",
    team: "CHI",
    bye: 10,
    projectedPoints: 331,
    consensusRank: 38,
    adp: 36.0,
    tier: 5,
    sos: 2,
    vbd: 82,
    vols: 30,
    fpVorp: 52,
    vbdRank: 59,
  },
  {
    id: "p39",
    name: "Breece Hall",
    pos: "RB",
    team: "NYJ",
    bye: 13,
    projectedPoints: 330,
    consensusRank: 39,
    adp: 45.0,
    tier: 5,
    sos: 3,
    injuryStatus: "Q",
    injuryDetails: "Groin",
    vbd: 241,
    vols: 74,
    fpVorp: 167,
    vbdRank: 17,
  },
  {
    id: "p40",
    name: "Jeremiyah Love",
    pos: "RB",
    team: "ARI",
    bye: 14,
    projectedPoints: 330,
    consensusRank: 40,
    adp: 50.0,
    tier: 5,
    sos: 2,
    injuryStatus: "Q",
    injuryDetails: "High Ankle",
    vbd: 211,
    vols: 59,
    fpVorp: 152,
    vbdRank: 24,
  },
  {
    id: "p41",
    name: "Emeka Egbuka",
    pos: "WR",
    team: "TB",
    bye: 10,
    projectedPoints: 330,
    consensusRank: 41,
    adp: 40.0,
    tier: 5,
    sos: 4,
    vbd: 108,
    vols: 22,
    fpVorp: 86,
    vbdRank: 48,
  },
  {
    id: "p42",
    name: "Kyren Williams",
    pos: "RB",
    team: "LAR",
    bye: 11,
    projectedPoints: 329,
    consensusRank: 42,
    adp: 55.0,
    tier: 5,
    sos: 5,
    vbd: 199,
    vols: 53,
    fpVorp: 146,
    vbdRank: 27,
  },
  {
    id: "p43",
    name: "Javonte Williams",
    pos: "RB",
    team: "DAL",
    bye: 14,
    projectedPoints: 328,
    consensusRank: 43,
    adp: 58.0,
    tier: 5,
    sos: 4,
    vbd: 209,
    vols: 58,
    fpVorp: 151,
    vbdRank: 25,
  },
  {
    id: "p44",
    name: "Joe Burrow",
    pos: "QB",
    team: "CIN",
    bye: 6,
    projectedPoints: 328,
    consensusRank: 44,
    adp: 34.0,
    tier: 5,
    sos: 3,
    vbd: 32,
    vols: 11,
    fpVorp: 21,
    vbdRank: 108,
  },
  {
    id: "p45",
    name: "Travis Etienne Jr.",
    pos: "RB",
    team: "NO",
    bye: 8,
    projectedPoints: 328,
    consensusRank: 45,
    adp: 56.0,
    tier: 5,
    sos: 3,
    injuryStatus: "Q",
    injuryDetails: "Ankle",
    vbd: 215,
    vols: 61,
    fpVorp: 154,
    vbdRank: 21,
  },
  {
    id: "p46",
    name: "Luther Burden III",
    pos: "WR",
    team: "CHI",
    bye: 10,
    projectedPoints: 327,
    consensusRank: 46,
    adp: 39.0,
    tier: 5,
    sos: 3,
    vbd: 76,
    vols: 6,
    fpVorp: 70,
    vbdRank: 62,
  },
  {
    id: "p47",
    name: "Terry McLaurin",
    pos: "WR",
    team: "WAS",
    bye: 7,
    projectedPoints: 326,
    consensusRank: 47,
    adp: 39.0,
    tier: 5,
    sos: 2,
    vbd: 76,
    vols: 6,
    fpVorp: 70,
    vbdRank: 61,
  },
  {
    id: "p48",
    name: "Davante Adams",
    pos: "WR",
    team: "LAR",
    bye: 11,
    projectedPoints: 326,
    consensusRank: 48,
    adp: 46.0,
    tier: 5,
    sos: 1,
    vbd: 116,
    vols: 26,
    fpVorp: 90,
    vbdRank: 44,
  },
  {
    id: "p49",
    name: "DJ Moore",
    pos: "WR",
    team: "BUF",
    bye: 7,
    projectedPoints: 326,
    consensusRank: 49,
    adp: 50.0,
    tier: 5,
    sos: 4,
    vbd: 68,
    vols: 2,
    fpVorp: 66,
    vbdRank: 67,
  },
  {
    id: "p50",
    name: "D'Andre Swift",
    pos: "RB",
    team: "CHI",
    bye: 10,
    projectedPoints: 325,
    consensusRank: 50,
    adp: 56.0,
    tier: 5,
    sos: 2,
    vbd: 197,
    vols: 52,
    fpVorp: 145,
    vbdRank: 28,
  },
  {
    id: "p51",
    name: "Jameson Williams",
    pos: "WR",
    team: "DET",
    bye: 6,
    projectedPoints: 324,
    consensusRank: 51,
    adp: 44.0,
    tier: 5,
    sos: 4,
    vbd: 100,
    vols: 18,
    fpVorp: 82,
    vbdRank: 50,
  },
  {
    id: "p52",
    name: "Tyler Warren",
    pos: "TE",
    team: "IND",
    bye: 13,
    projectedPoints: 324,
    consensusRank: 52,
    adp: 53.0,
    tier: 6,
    sos: 3,
    injuryStatus: "Q",
    injuryDetails: "Groin",
    vbd: 62,
    vols: 20,
    fpVorp: 42,
    vbdRank: 73,
  },
  {
    id: "p53",
    name: "Bucky Irving",
    pos: "RB",
    team: "TB",
    bye: 10,
    projectedPoints: 324,
    consensusRank: 53,
    adp: 59.0,
    tier: 6,
    sos: 2,
    vbd: 171,
    vols: 39,
    fpVorp: 132,
    vbdRank: 33,
  },
  {
    id: "p54",
    name: "Cam Skattebo",
    pos: "RB",
    team: "NYG",
    bye: 8,
    projectedPoints: 323,
    consensusRank: 54,
    adp: 71.0,
    tier: 6,
    sos: 4,
    vbd: 215,
    vols: 61,
    fpVorp: 154,
    vbdRank: 22,
  },
  {
    id: "p55",
    name: "Christian Watson",
    pos: "WR",
    team: "GB",
    bye: 11,
    projectedPoints: 322,
    consensusRank: 55,
    adp: 45.0,
    tier: 6,
    sos: 5,
    injuryStatus: "Q",
    injuryDetails: "Hamstring",
    vbd: 64,
    vols: 0,
    fpVorp: 64,
    vbdRank: 70,
  },
  {
    id: "p56",
    name: "Jalen Hurts",
    pos: "QB",
    team: "PHI",
    bye: 10,
    projectedPoints: 322,
    consensusRank: 56,
    adp: 50.0,
    tier: 6,
    sos: 5,
    vbd: 48,
    vols: 19,
    fpVorp: 29,
    vbdRank: 88,
  },
  {
    id: "p57",
    name: "Jayden Daniels",
    pos: "QB",
    team: "WAS",
    bye: 7,
    projectedPoints: 322,
    consensusRank: 57,
    adp: 53.0,
    tier: 6,
    sos: 2,
    vbd: 30,
    vols: 10,
    fpVorp: 20,
    vbdRank: 112,
  },
  {
    id: "p58",
    name: "Rome Odunze",
    pos: "WR",
    team: "CHI",
    bye: 10,
    projectedPoints: 321,
    consensusRank: 58,
    adp: 57.0,
    tier: 6,
    sos: 3,
    vbd: 60,
    vols: 0,
    fpVorp: 60,
    vbdRank: 77,
  },
  {
    id: "p59",
    name: "Parker Washington",
    pos: "WR",
    team: "JAC",
    bye: 7,
    projectedPoints: 320,
    consensusRank: 59,
    adp: 55.0,
    tier: 6,
    sos: 4,
    vbd: 64,
    vols: 0,
    fpVorp: 64,
    vbdRank: 71,
  },
  {
    id: "p60",
    name: "David Montgomery",
    pos: "RB",
    team: "HOU",
    bye: 8,
    projectedPoints: 320,
    consensusRank: 60,
    adp: 71.0,
    tier: 6,
    sos: 4,
    vbd: 153,
    vols: 30,
    fpVorp: 123,
    vbdRank: 36,
  },
  {
    id: "p61",
    name: "Quinshon Judkins",
    pos: "RB",
    team: "CLE",
    bye: 11,
    projectedPoints: 320,
    consensusRank: 61,
    adp: 77.0,
    tier: 6,
    sos: 3,
    vbd: 165,
    vols: 36,
    fpVorp: 129,
    vbdRank: 35,
  },
  {
    id: "p62",
    name: "Mike Evans",
    pos: "WR",
    team: "SF",
    bye: 8,
    projectedPoints: 319,
    consensusRank: 62,
    adp: 57.0,
    tier: 6,
    sos: 2,
    vbd: 70,
    vols: 3,
    fpVorp: 67,
    vbdRank: 66,
  },
  {
    id: "p63",
    name: "Caleb Williams",
    pos: "QB",
    team: "CHI",
    bye: 10,
    projectedPoints: 318,
    consensusRank: 63,
    adp: 48.0,
    tier: 6,
    sos: 3,
    vbd: 10,
    vols: 0,
    fpVorp: 10,
    vbdRank: 144,
  },
  {
    id: "p64",
    name: "Bhayshul Tuten",
    pos: "RB",
    team: "JAC",
    bye: 7,
    projectedPoints: 318,
    consensusRank: 64,
    adp: 72.0,
    tier: 6,
    sos: 4,
    vbd: 123,
    vols: 15,
    fpVorp: 108,
    vbdRank: 43,
  },
  {
    id: "p65",
    name: "Jadarian Price",
    pos: "RB",
    team: "SEA",
    bye: 11,
    projectedPoints: 318,
    consensusRank: 65,
    adp: 73.0,
    tier: 6,
    sos: 4,
    vbd: 83,
    vols: 0,
    fpVorp: 83,
    vbdRank: 58,
  },
  {
    id: "p66",
    name: "Carnell Tate",
    pos: "WR",
    team: "TEN",
    bye: 9,
    projectedPoints: 317,
    consensusRank: 66,
    adp: 57.0,
    tier: 6,
    sos: 3,
    vbd: 42,
    vols: 0,
    fpVorp: 42,
    vbdRank: 95,
  },
  {
    id: "p67",
    name: "Marvin Harrison Jr.",
    pos: "WR",
    team: "ARI",
    bye: 14,
    projectedPoints: 316,
    consensusRank: 67,
    adp: 62.0,
    tier: 6,
    sos: 2,
    vbd: 58,
    vols: 0,
    fpVorp: 58,
    vbdRank: 79,
  },
  {
    id: "p68",
    name: "TreVeyon Henderson",
    pos: "RB",
    team: "NE",
    bye: 11,
    projectedPoints: 316,
    consensusRank: 68,
    adp: 76.0,
    tier: 6,
    sos: 2,
    vbd: 115,
    vols: 11,
    fpVorp: 104,
    vbdRank: 45,
  },
  {
    id: "p69",
    name: "Justin Herbert",
    pos: "QB",
    team: "LAC",
    bye: 7,
    projectedPoints: 316,
    consensusRank: 69,
    adp: 55.0,
    tier: 6,
    sos: 2,
    vbd: 10,
    vols: 0,
    fpVorp: 10,
    vbdRank: 143,
  },
  {
    id: "p70",
    name: "Rhamondre Stevenson",
    pos: "RB",
    team: "NE",
    bye: 11,
    projectedPoints: 315,
    consensusRank: 70,
    adp: 76.0,
    tier: 6,
    sos: 2,
    vbd: 139,
    vols: 23,
    fpVorp: 116,
    vbdRank: 39,
  },
  {
    id: "p71",
    name: "Jaylen Warren",
    pos: "RB",
    team: "PIT",
    bye: 9,
    projectedPoints: 314,
    consensusRank: 71,
    adp: 74.0,
    tier: 6,
    sos: 2,
    vbd: 145,
    vols: 26,
    fpVorp: 119,
    vbdRank: 37,
  },
  {
    id: "p72",
    name: "Chris Godwin Jr.",
    pos: "WR",
    team: "TB",
    bye: 10,
    projectedPoints: 314,
    consensusRank: 72,
    adp: 57.0,
    tier: 6,
    sos: 4,
    vbd: 48,
    vols: 0,
    fpVorp: 48,
    vbdRank: 89,
  },
  {
    id: "p73",
    name: "Trevor Lawrence",
    pos: "QB",
    team: "JAX",
    bye: 7,
    projectedPoints: 314,
    consensusRank: 73,
    adp: 58.0,
    tier: 6,
    sos: 4,
    vbd: 28,
    vols: 9,
    fpVorp: 19,
    vbdRank: 117,
  },
  {
    id: "p74",
    name: "Harold Fannin Jr.",
    pos: "TE",
    team: "CLE",
    bye: 11,
    projectedPoints: 313,
    consensusRank: 74,
    adp: 82.0,
    tier: 7,
    sos: 3,
    vbd: 56,
    vols: 17,
    fpVorp: 39,
    vbdRank: 80,
  },
  {
    id: "p75",
    name: "Dak Prescott",
    pos: "QB",
    team: "DAL",
    bye: 14,
    projectedPoints: 312,
    consensusRank: 75,
    adp: 76.0,
    tier: 7,
    sos: 2,
    vbd: 36,
    vols: 13,
    fpVorp: 23,
    vbdRank: 103,
  },
  {
    id: "p76",
    name: "Kyle Pitts Sr.",
    pos: "TE",
    team: "ATL",
    bye: 11,
    projectedPoints: 312,
    consensusRank: 76,
    adp: 81.0,
    tier: 7,
    sos: 3,
    vbd: 22,
    vols: 0,
    fpVorp: 22,
    vbdRank: 125,
  },
  {
    id: "p77",
    name: "Tucker Kraft",
    pos: "TE",
    team: "GB",
    bye: 11,
    projectedPoints: 312,
    consensusRank: 77,
    adp: 85.0,
    tier: 7,
    sos: 2,
    injuryStatus: "Q",
    injuryDetails: "Knee",
    vbd: 15,
    vols: 0,
    fpVorp: 15,
    vbdRank: 135,
  },
  {
    id: "p78",
    name: "DK Metcalf",
    pos: "WR",
    team: "PIT",
    bye: 9,
    projectedPoints: 311,
    consensusRank: 78,
    adp: 76.0,
    tier: 7,
    sos: 3,
    vbd: 61,
    vols: 0,
    fpVorp: 61,
    vbdRank: 74,
  },
  {
    id: "p79",
    name: "Brian Thomas Jr.",
    pos: "WR",
    team: "JAC",
    bye: 7,
    projectedPoints: 310,
    consensusRank: 79,
    adp: 74.0,
    tier: 7,
    sos: 4,
    vbd: 40,
    vols: 0,
    fpVorp: 40,
    vbdRank: 97,
  },
  {
    id: "p80",
    name: "Michael Pittman Jr.",
    pos: "WR",
    team: "PIT",
    bye: 9,
    projectedPoints: 310,
    consensusRank: 80,
    adp: 66.0,
    tier: 7,
    sos: 3,
    vbd: 54,
    vols: 0,
    fpVorp: 54,
    vbdRank: 83,
  },
  {
    id: "p81",
    name: "Tony Pollard",
    pos: "RB",
    team: "TEN",
    bye: 9,
    projectedPoints: 310,
    consensusRank: 81,
    adp: 86.0,
    tier: 7,
    sos: 3,
    vbd: 105,
    vols: 6,
    fpVorp: 99,
    vbdRank: 49,
  },
  {
    id: "p82",
    name: "Courtland Sutton",
    pos: "WR",
    team: "DEN",
    bye: 10,
    projectedPoints: 309,
    consensusRank: 82,
    adp: 87.0,
    tier: 7,
    sos: 2,
    vbd: 53,
    vols: 0,
    fpVorp: 53,
    vbdRank: 84,
  },
  {
    id: "p83",
    name: "Wan'Dale Robinson",
    pos: "WR",
    team: "TEN",
    bye: 9,
    projectedPoints: 308,
    consensusRank: 83,
    adp: 63.0,
    tier: 7,
    sos: 3,
    vbd: 41,
    vols: 0,
    fpVorp: 41,
    vbdRank: 96,
  },
  {
    id: "p84",
    name: "Rico Dowdle",
    pos: "RB",
    team: "PIT",
    bye: 9,
    projectedPoints: 308,
    consensusRank: 84,
    adp: 89.0,
    tier: 7,
    sos: 2,
    vbd: 93,
    vols: 0,
    fpVorp: 93,
    vbdRank: 54,
  },
  {
    id: "p85",
    name: "Sam LaPorta",
    pos: "TE",
    team: "DET",
    bye: 6,
    projectedPoints: 308,
    consensusRank: 85,
    adp: 97.0,
    tier: 7,
    sos: 3,
    injuryStatus: "Q",
    injuryDetails: "Hip",
    vbd: 44,
    vols: 11,
    fpVorp: 33,
    vbdRank: 92,
  },
  {
    id: "p86",
    name: "Jonathon Brooks",
    pos: "RB",
    team: "CAR",
    bye: 5,
    projectedPoints: 307,
    consensusRank: 86,
    adp: 91.0,
    tier: 7,
    sos: 1,
    vbd: 66,
    vols: 0,
    fpVorp: 66,
    vbdRank: 69,
  },
  {
    id: "p87",
    name: "Michael Wilson",
    pos: "WR",
    team: "ARI",
    bye: 14,
    projectedPoints: 306,
    consensusRank: 87,
    adp: 88.0,
    tier: 7,
    sos: 2,
    vbd: 45,
    vols: 0,
    fpVorp: 45,
    vbdRank: 91,
  },
  {
    id: "p88",
    name: "Josh Downs",
    pos: "WR",
    team: "IND",
    bye: 13,
    projectedPoints: 306,
    consensusRank: 88,
    adp: 57.0,
    tier: 7,
    sos: 4,
    vbd: 26,
    vols: 0,
    fpVorp: 26,
    vbdRank: 121,
  },
  {
    id: "p89",
    name: "Quentin Johnston",
    pos: "WR",
    team: "LAC",
    bye: 7,
    projectedPoints: 306,
    consensusRank: 89,
    adp: 74.0,
    tier: 7,
    sos: 2,
    vbd: 38,
    vols: 0,
    fpVorp: 38,
    vbdRank: 99,
  },
  {
    id: "p90",
    name: "RJ Harvey",
    pos: "RB",
    team: "DEN",
    bye: 10,
    projectedPoints: 305,
    consensusRank: 90,
    adp: 95.0,
    tier: 7,
    sos: 2,
    vbd: 82,
    vols: 0,
    fpVorp: 82,
    vbdRank: 60,
  },
  {
    id: "p91",
    name: "Brock Purdy",
    pos: "QB",
    team: "SF",
    bye: 8,
    projectedPoints: 304,
    consensusRank: 91,
    adp: 67.0,
    tier: 7,
    sos: 1,
    vbd: 26,
    vols: 8,
    fpVorp: 18,
    vbdRank: 118,
  },
  {
    id: "p92",
    name: "Stefon Diggs",
    pos: "WR",
    team: "WAS",
    bye: 7,
    projectedPoints: 304,
    consensusRank: 92,
    adp: 86.0,
    tier: 7,
    sos: 2,
    vbd: 32,
    vols: 0,
    fpVorp: 32,
    vbdRank: 110,
  },
  {
    id: "p93",
    name: "Kenny Gainwell",
    pos: "RB",
    team: "TB",
    bye: 10,
    projectedPoints: 304,
    consensusRank: 93,
    adp: 93.0,
    tier: 7,
    sos: 2,
    vbd: 74,
    vols: 0,
    fpVorp: 74,
    vbdRank: 64,
  },
  {
    id: "p94",
    name: "Bo Nix",
    pos: "QB",
    team: "DEN",
    bye: 10,
    projectedPoints: 303,
    consensusRank: 94,
    adp: 74.0,
    tier: 7,
    sos: 3,
    vbd: 2,
    vols: 0,
    fpVorp: 2,
    vbdRank: 164,
  },
  {
    id: "p95",
    name: "Jaxson Dart",
    pos: "QB",
    team: "NYG",
    bye: 8,
    projectedPoints: 302,
    consensusRank: 95,
    adp: 94.0,
    tier: 7,
    sos: 4,
    vbd: 8,
    vols: 0,
    fpVorp: 8,
    vbdRank: 151,
  },
  {
    id: "p96",
    name: "George Kittle",
    pos: "TE",
    team: "SF",
    bye: 8,
    projectedPoints: 302,
    consensusRank: 96,
    adp: 110.0,
    tier: 7,
    sos: 3,
    vbd: 34,
    vols: 6,
    fpVorp: 28,
    vbdRank: 106,
  },
  {
    id: "p97",
    name: "Travis Kelce",
    pos: "TE",
    team: "KC",
    bye: 5,
    projectedPoints: 302,
    consensusRank: 97,
    adp: 102.0,
    tier: 7,
    sos: 4,
    vbd: 32,
    vols: 5,
    fpVorp: 27,
    vbdRank: 109,
  },
  {
    id: "p98",
    name: "Chuba Hubbard",
    pos: "RB",
    team: "CAR",
    bye: 5,
    projectedPoints: 301,
    consensusRank: 98,
    adp: 106.0,
    tier: 7,
    sos: 1,
    vbd: 99,
    vols: 3,
    fpVorp: 96,
    vbdRank: 51,
  },
  {
    id: "p99",
    name: "Alec Pierce",
    pos: "WR",
    team: "IND",
    bye: 13,
    projectedPoints: 300,
    consensusRank: 99,
    adp: 107.0,
    tier: 7,
    sos: 4,
    vbd: 62,
    vols: 0,
    fpVorp: 62,
    vbdRank: 72,
  },
  {
    id: "p100",
    name: "J.K. Dobbins",
    pos: "RB",
    team: "DEN",
    bye: 10,
    projectedPoints: 300,
    consensusRank: 100,
    adp: 111.0,
    tier: 8,
    sos: 2,
    vbd: 97,
    vols: 2,
    fpVorp: 95,
    vbdRank: 52,
  },
  {
    id: "p101",
    name: "Patrick Mahomes II",
    pos: "QB",
    team: "KC",
    bye: 5,
    projectedPoints: 300,
    consensusRank: 101,
    adp: 93.0,
    tier: 8,
    sos: 2,
    vbd: 16,
    vols: 3,
    fpVorp: 13,
    vbdRank: 133,
  },
  {
    id: "p102",
    name: "Jayden Reed",
    pos: "WR",
    team: "GB",
    bye: 11,
    projectedPoints: 299,
    consensusRank: 102,
    adp: 83.0,
    tier: 8,
    sos: 5,
    vbd: 42,
    vols: 0,
    fpVorp: 42,
    vbdRank: 94,
  },
  {
    id: "p103",
    name: "Jared Goff",
    pos: "QB",
    team: "DET",
    bye: 6,
    projectedPoints: 298,
    consensusRank: 103,
    adp: 80.0,
    tier: 8,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 172,
  },
  {
    id: "p104",
    name: "Matthew Stafford",
    pos: "QB",
    team: "LAR",
    bye: 11,
    projectedPoints: 298,
    consensusRank: 104,
    adp: 111.0,
    tier: 8,
    sos: 3,
    vbd: 5,
    vols: 0,
    fpVorp: 5,
    vbdRank: 160,
  },
  {
    id: "p105",
    name: "Jakobi Meyers",
    pos: "WR",
    team: "JAC",
    bye: 7,
    projectedPoints: 298,
    consensusRank: 105,
    adp: 87.0,
    tier: 8,
    sos: 4,
    vbd: 47,
    vols: 0,
    fpVorp: 47,
    vbdRank: 90,
  },
  {
    id: "p106",
    name: "Blake Corum",
    pos: "RB",
    team: "LAR",
    bye: 11,
    projectedPoints: 297,
    consensusRank: 106,
    adp: 113.0,
    tier: 8,
    sos: 5,
    vbd: 54,
    vols: 0,
    fpVorp: 54,
    vbdRank: 82,
  },
  {
    id: "p107",
    name: "KC Concepcion",
    pos: "WR",
    team: "CLE",
    bye: 11,
    projectedPoints: 296,
    consensusRank: 107,
    adp: 89.0,
    tier: 8,
    sos: 3,
    vbd: 18,
    vols: 0,
    fpVorp: 18,
    vbdRank: 132,
  },
  {
    id: "p108",
    name: "Makai Lemon",
    pos: "WR",
    team: "PHI",
    bye: 10,
    projectedPoints: 296,
    consensusRank: 108,
    adp: 103.0,
    tier: 8,
    sos: 4,
    vbd: 21,
    vols: 0,
    fpVorp: 21,
    vbdRank: 126,
  },
  {
    id: "p109",
    name: "Jordan Addison",
    pos: "WR",
    team: "MIN",
    bye: 6,
    projectedPoints: 296,
    consensusRank: 109,
    adp: 111.0,
    tier: 8,
    sos: 5,
    vbd: 42,
    vols: 0,
    fpVorp: 42,
    vbdRank: 93,
  },
  {
    id: "p110",
    name: "MarShawn Lloyd",
    pos: "RB",
    team: "GB",
    bye: 11,
    projectedPoints: 295,
    consensusRank: 110,
    adp: 120.0,
    tier: 8,
    sos: 4,
    vbd: 53,
    vols: 0,
    fpVorp: 53,
    vbdRank: 85,
  },
  {
    id: "p111",
    name: "Rachaad White",
    pos: "RB",
    team: "WAS",
    bye: 7,
    projectedPoints: 294,
    consensusRank: 111,
    adp: 104.0,
    tier: 8,
    sos: 4,
    vbd: 73,
    vols: 0,
    fpVorp: 73,
    vbdRank: 65,
  },
  {
    id: "p112",
    name: "Dalton Kincaid",
    pos: "TE",
    team: "BUF",
    bye: 7,
    projectedPoints: 294,
    consensusRank: 112,
    adp: 102.0,
    tier: 8,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 192,
  },
  {
    id: "p113",
    name: "Jordan Mason",
    pos: "RB",
    team: "MIN",
    bye: 6,
    projectedPoints: 294,
    consensusRank: 113,
    adp: 124.0,
    tier: 8,
    sos: 4,
    vbd: 60,
    vols: 0,
    fpVorp: 60,
    vbdRank: 78,
  },
  {
    id: "p114",
    name: "Kyler Murray",
    pos: "QB",
    team: "MIN",
    bye: 6,
    projectedPoints: 293,
    consensusRank: 114,
    adp: 91.0,
    tier: 8,
    sos: 5,
    vbd: 6,
    vols: 0,
    fpVorp: 6,
    vbdRank: 154,
  },
  {
    id: "p115",
    name: "Jacory Croskey-Merritt",
    pos: "RB",
    team: "WAS",
    bye: 7,
    projectedPoints: 292,
    consensusRank: 115,
    adp: 120.0,
    tier: 8,
    sos: 4,
    vbd: 66,
    vols: 0,
    fpVorp: 66,
    vbdRank: 68,
  },
  {
    id: "p116",
    name: "Jordan Love",
    pos: "QB",
    team: "GB",
    bye: 11,
    projectedPoints: 292,
    consensusRank: 116,
    adp: 85.0,
    tier: 8,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 223,
  },
  {
    id: "p117",
    name: "Aaron Jones Sr.",
    pos: "RB",
    team: "MIN",
    bye: 6,
    projectedPoints: 292,
    consensusRank: 117,
    adp: 114.0,
    tier: 8,
    sos: 4,
    vbd: 89,
    vols: 0,
    fpVorp: 89,
    vbdRank: 55,
  },
  {
    id: "p118",
    name: "Baker Mayfield",
    pos: "QB",
    team: "TB",
    bye: 10,
    projectedPoints: 291,
    consensusRank: 118,
    adp: 96.0,
    tier: 8,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 201,
  },
  {
    id: "p119",
    name: "Isaiah Likely",
    pos: "TE",
    team: "NYG",
    bye: 8,
    projectedPoints: 290,
    consensusRank: 119,
    adp: 133.0,
    tier: 8,
    sos: 3,
    vbd: 2,
    vols: 0,
    fpVorp: 2,
    vbdRank: 169,
  },
  {
    id: "p120",
    name: "Kyle Monangai",
    pos: "RB",
    team: "CHI",
    bye: 10,
    projectedPoints: 290,
    consensusRank: 120,
    adp: 134.0,
    tier: 8,
    sos: 2,
    vbd: 75,
    vols: 0,
    fpVorp: 75,
    vbdRank: 63,
  },
  {
    id: "p121",
    name: "Dallas Goedert",
    pos: "TE",
    team: "PHI",
    bye: 10,
    projectedPoints: 290,
    consensusRank: 121,
    adp: 130.0,
    tier: 8,
    sos: 4,
    vbd: 30,
    vols: 4,
    fpVorp: 26,
    vbdRank: 114,
  },
  {
    id: "p122",
    name: "Jake Ferguson",
    pos: "TE",
    team: "DAL",
    bye: 14,
    projectedPoints: 289,
    consensusRank: 122,
    adp: 127.0,
    tier: 8,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 177,
  },
  {
    id: "p123",
    name: "De'Zhaun Stribling",
    pos: "WR",
    team: "SF",
    bye: 8,
    projectedPoints: 288,
    consensusRank: 123,
    adp: 135.0,
    tier: 8,
    sos: 2,
    vbd: 25,
    vols: 0,
    fpVorp: 25,
    vbdRank: 122,
  },
  {
    id: "p124",
    name: "Khalil Shakir",
    pos: "WR",
    team: "BUF",
    bye: 7,
    projectedPoints: 288,
    consensusRank: 124,
    adp: 100.0,
    tier: 8,
    sos: 4,
    injuryStatus: "Q",
    injuryDetails: "Lower Leg",
    vbd: 37,
    vols: 0,
    fpVorp: 37,
    vbdRank: 101,
  },
  {
    id: "p125",
    name: "Tyler Shough",
    pos: "QB",
    team: "NO",
    bye: 8,
    projectedPoints: 288,
    consensusRank: 125,
    adp: 96.0,
    tier: 8,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 216,
  },
  {
    id: "p126",
    name: "Jalen Coker",
    pos: "WR",
    team: "CAR",
    bye: 5,
    projectedPoints: 287,
    consensusRank: 126,
    adp: 110.0,
    tier: 8,
    sos: 2,
    vbd: 11,
    vols: 0,
    fpVorp: 11,
    vbdRank: 142,
  },
  {
    id: "p127",
    name: "Matthew Golden",
    pos: "WR",
    team: "GB",
    bye: 11,
    projectedPoints: 286,
    consensusRank: 127,
    adp: 127.0,
    tier: 8,
    sos: 5,
    vbd: 26,
    vols: 0,
    fpVorp: 26,
    vbdRank: 120,
  },
  {
    id: "p128",
    name: "Juwan Johnson",
    pos: "TE",
    team: "NO",
    bye: 8,
    projectedPoints: 286,
    consensusRank: 128,
    adp: 107.0,
    tier: 8,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 200,
  },
  {
    id: "p129",
    name: "Romeo Doubs",
    pos: "WR",
    team: "NE",
    bye: 11,
    projectedPoints: 286,
    consensusRank: 129,
    adp: 129.0,
    tier: 8,
    sos: 2,
    vbd: 33,
    vols: 0,
    fpVorp: 33,
    vbdRank: 107,
  },
  {
    id: "p130",
    name: "Malik Willis",
    pos: "QB",
    team: "MIA",
    bye: 6,
    projectedPoints: 285,
    consensusRank: 130,
    adp: 92.0,
    tier: 8,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 240,
  },
  {
    id: "p131",
    name: "Xavier Worthy",
    pos: "WR",
    team: "KC",
    bye: 5,
    projectedPoints: 284,
    consensusRank: 131,
    adp: 132.0,
    tier: 8,
    sos: 2,
    vbd: 31,
    vols: 0,
    fpVorp: 31,
    vbdRank: 111,
  },
  {
    id: "p132",
    name: "Mark Andrews",
    pos: "TE",
    team: "BAL",
    bye: 13,
    projectedPoints: 284,
    consensusRank: 132,
    adp: 136.0,
    tier: 9,
    sos: 4,
    vbd: 13,
    vols: 0,
    fpVorp: 13,
    vbdRank: 140,
  },
  {
    id: "p133",
    name: "Woody Marks",
    pos: "RB",
    team: "HOU",
    bye: 8,
    projectedPoints: 284,
    consensusRank: 133,
    adp: 135.0,
    tier: 9,
    sos: 4,
    vbd: 51,
    vols: 0,
    fpVorp: 51,
    vbdRank: 86,
  },
  {
    id: "p134",
    name: "Tyler Allgeier",
    pos: "RB",
    team: "ARI",
    bye: 14,
    projectedPoints: 283,
    consensusRank: 134,
    adp: 127.0,
    tier: 9,
    sos: 2,
    vbd: 20,
    vols: 0,
    fpVorp: 20,
    vbdRank: 130,
  },
  {
    id: "p135",
    name: "Sam Darnold",
    pos: "QB",
    team: "SEA",
    bye: 11,
    projectedPoints: 282,
    consensusRank: 135,
    adp: 86.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 230,
  },
  {
    id: "p136",
    name: "Tyjae Spears",
    pos: "RB",
    team: "TEN",
    bye: 9,
    projectedPoints: 282,
    consensusRank: 136,
    adp: 129.0,
    tier: 9,
    sos: 3,
    vbd: 49,
    vols: 0,
    fpVorp: 49,
    vbdRank: 87,
  },
  {
    id: "p137",
    name: "Chris Rodriguez Jr.",
    pos: "RB",
    team: "JAC",
    bye: 7,
    projectedPoints: 282,
    consensusRank: 137,
    adp: 140.0,
    tier: 9,
    sos: 4,
    vbd: 8,
    vols: 0,
    fpVorp: 8,
    vbdRank: 153,
  },
  {
    id: "p138",
    name: "Jordyn Tyson",
    pos: "WR",
    team: "NO",
    bye: 8,
    projectedPoints: 281,
    consensusRank: 138,
    adp: 130.0,
    tier: 9,
    sos: 3,
    injuryStatus: "IR",
    injuryDetails: "Hamstring",
    vbd: 2,
    vols: 0,
    fpVorp: 2,
    vbdRank: 170,
  },
  {
    id: "p139",
    name: "C.J. Stroud",
    pos: "QB",
    team: "HOU",
    bye: 8,
    projectedPoints: 280,
    consensusRank: 139,
    adp: 97.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 255,
  },
  {
    id: "p140",
    name: "Deebo Samuel Sr.",
    pos: "WR",
    team: "SF",
    bye: 8,
    projectedPoints: 280,
    consensusRank: 140,
    adp: 145.0,
    tier: 9,
    sos: 2,
    vbd: 30,
    vols: 0,
    fpVorp: 30,
    vbdRank: 115,
  },
  {
    id: "p141",
    name: "Daniel Jones",
    pos: "QB",
    team: "IND",
    bye: 13,
    projectedPoints: 280,
    consensusRank: 141,
    adp: 104.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 235,
  },
  {
    id: "p142",
    name: "Jonah Coleman",
    pos: "RB",
    team: "DEN",
    bye: 10,
    projectedPoints: 279,
    consensusRank: 142,
    adp: 132.0,
    tier: 9,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 253,
  },
  {
    id: "p143",
    name: "Rashid Shaheed",
    pos: "WR",
    team: "SEA",
    bye: 11,
    projectedPoints: 278,
    consensusRank: 143,
    adp: 142.0,
    tier: 9,
    sos: 3,
    vbd: 20,
    vols: 0,
    fpVorp: 20,
    vbdRank: 128,
  },
  {
    id: "p144",
    name: "Dylan Sampson",
    pos: "RB",
    team: "CLE",
    bye: 11,
    projectedPoints: 278,
    consensusRank: 144,
    adp: 118.0,
    tier: 9,
    sos: 3,
    vbd: 29,
    vols: 0,
    fpVorp: 29,
    vbdRank: 116,
  },
  {
    id: "p145",
    name: "Keaton Mitchell",
    pos: "RB",
    team: "LAC",
    bye: 7,
    projectedPoints: 278,
    consensusRank: 145,
    adp: 129.0,
    tier: 9,
    sos: 3,
    injuryStatus: "PUP",
    injuryDetails: "Knee",
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 179,
  },
  {
    id: "p146",
    name: "Mike Washington Jr.",
    pos: "RB",
    team: "LV",
    bye: 13,
    projectedPoints: 277,
    consensusRank: 146,
    adp: 154.0,
    tier: 9,
    sos: 2,
    vbd: 5,
    vols: 0,
    fpVorp: 5,
    vbdRank: 161,
  },
  {
    id: "p147",
    name: "Zach Charbonnet",
    pos: "RB",
    team: "SEA",
    bye: 11,
    projectedPoints: 276,
    consensusRank: 147,
    adp: 149.0,
    tier: 9,
    sos: 4,
    vbd: 37,
    vols: 0,
    fpVorp: 37,
    vbdRank: 102,
  },
  {
    id: "p148",
    name: "Denzel Boston",
    pos: "WR",
    team: "CLE",
    bye: 11,
    projectedPoints: 276,
    consensusRank: 148,
    adp: 124.0,
    tier: 9,
    sos: 3,
    vbd: 1,
    vols: 0,
    fpVorp: 1,
    vbdRank: 171,
  },
  {
    id: "p149",
    name: "Cam Ward",
    pos: "QB",
    team: "TEN",
    bye: 9,
    projectedPoints: 276,
    consensusRank: 149,
    adp: 67.0,
    tier: 9,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 335,
  },
  {
    id: "p150",
    name: "Josh Jacobs",
    pos: "RB",
    team: "GB",
    bye: 11,
    projectedPoints: 275,
    consensusRank: 150,
    adp: 230.0,
    tier: 9,
    sos: 4,
    vbd: 61,
    vols: 0,
    fpVorp: 61,
    vbdRank: 75,
  },
  {
    id: "p151",
    name: "Tre Tucker",
    pos: "WR",
    team: "LV",
    bye: 13,
    projectedPoints: 274,
    consensusRank: 151,
    adp: 129.0,
    tier: 9,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 196,
  },
  {
    id: "p152",
    name: "Brenton Strange",
    pos: "TE",
    team: "JAC",
    bye: 7,
    projectedPoints: 274,
    consensusRank: 152,
    adp: 147.0,
    tier: 9,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 199,
  },
  {
    id: "p153",
    name: "Dalton Schultz",
    pos: "TE",
    team: "HOU",
    bye: 8,
    projectedPoints: 274,
    consensusRank: 153,
    adp: 131.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 228,
  },
  {
    id: "p154",
    name: "Chig Okonkwo",
    pos: "TE",
    team: "WAS",
    bye: 7,
    projectedPoints: 273,
    consensusRank: 154,
    adp: 107.0,
    tier: 9,
    sos: 1,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 271,
  },
  {
    id: "p155",
    name: "Houston Texans",
    pos: "DST",
    team: "HOU",
    bye: 8,
    projectedPoints: 102,
    consensusRank: 155,
    adp: 209.0,
    tier: 9,
    sos: 2,
    vbd: 36,
    vols: 18,
    fpVorp: 18,
    vbdRank: 105,
  },
  {
    id: "p156",
    name: "Hunter Henry",
    pos: "TE",
    team: "NE",
    bye: 11,
    projectedPoints: 272,
    consensusRank: 156,
    adp: 156.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 183,
  },
  {
    id: "p157",
    name: "Bryce Young",
    pos: "QB",
    team: "CAR",
    bye: 5,
    projectedPoints: 272,
    consensusRank: 157,
    adp: 102.0,
    tier: 9,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 269,
  },
  {
    id: "p158",
    name: "Alvin Kamara",
    pos: "RB",
    team: "NO",
    bye: 8,
    projectedPoints: 271,
    consensusRank: 158,
    adp: 158.0,
    tier: 9,
    sos: 3,
    injuryStatus: "IR",
    injuryDetails: "Ankle/Knee",
    vbd: 38,
    vols: 0,
    fpVorp: 38,
    vbdRank: 100,
  },
  {
    id: "p159",
    name: "Tank Bigsby",
    pos: "RB",
    team: "PHI",
    bye: 10,
    projectedPoints: 270,
    consensusRank: 159,
    adp: 149.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 184,
  },
  {
    id: "p160",
    name: "Adonai Mitchell",
    pos: "WR",
    team: "NYJ",
    bye: 13,
    projectedPoints: 270,
    consensusRank: 160,
    adp: 85.0,
    tier: 9,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 268,
  },
  {
    id: "p161",
    name: "Kayshon Boutte",
    pos: "WR",
    team: "HOU",
    bye: 8,
    projectedPoints: 270,
    consensusRank: 161,
    adp: 125.0,
    tier: 9,
    sos: 3,
    vbd: 3,
    vols: 0,
    fpVorp: 3,
    vbdRank: 163,
  },
  {
    id: "p162",
    name: "Tyrone Tracy Jr.",
    pos: "RB",
    team: "NYG",
    bye: 8,
    projectedPoints: 269,
    consensusRank: 162,
    adp: 132.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 193,
  },
  {
    id: "p163",
    name: "Jerry Jeudy",
    pos: "WR",
    team: "CLE",
    bye: 11,
    projectedPoints: 268,
    consensusRank: 163,
    adp: 147.0,
    tier: 10,
    sos: 3,
    vbd: 16,
    vols: 0,
    fpVorp: 16,
    vbdRank: 134,
  },
  {
    id: "p164",
    name: "Denver Broncos",
    pos: "DST",
    team: "DEN",
    bye: 10,
    projectedPoints: 95,
    consensusRank: 164,
    adp: 212.0,
    tier: 10,
    sos: 4,
    vbd: 30,
    vols: 15,
    fpVorp: 15,
    vbdRank: 113,
  },
  {
    id: "p165",
    name: "Jalen McMillan",
    pos: "WR",
    team: "TB",
    bye: 10,
    projectedPoints: 268,
    consensusRank: 165,
    adp: 124.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 178,
  },
  {
    id: "p166",
    name: "Los Angeles Rams",
    pos: "DST",
    team: "LAR",
    bye: 11,
    projectedPoints: 93,
    consensusRank: 166,
    adp: 224.0,
    tier: 10,
    sos: 2,
    vbd: 14,
    vols: 7,
    fpVorp: 7,
    vbdRank: 137,
  },
  {
    id: "p167",
    name: "Braelon Allen",
    pos: "RB",
    team: "NYJ",
    bye: 13,
    projectedPoints: 266,
    consensusRank: 167,
    adp: 134.0,
    tier: 10,
    sos: 3,
    vbd: 14,
    vols: 0,
    fpVorp: 14,
    vbdRank: 139,
  },
  {
    id: "p168",
    name: "Brian Robinson Jr.",
    pos: "RB",
    team: "ATL",
    bye: 11,
    projectedPoints: 266,
    consensusRank: 168,
    adp: 171.0,
    tier: 10,
    sos: 2,
    vbd: 6,
    vols: 0,
    fpVorp: 6,
    vbdRank: 158,
  },
  {
    id: "p169",
    name: "Emmett Johnson",
    pos: "RB",
    team: "KC",
    bye: 5,
    projectedPoints: 266,
    consensusRank: 169,
    adp: 153.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 302,
  },
  {
    id: "p170",
    name: "Seattle Seahawks",
    pos: "DST",
    team: "SEA",
    bye: 11,
    projectedPoints: 90,
    consensusRank: 170,
    adp: 216.0,
    tier: 10,
    sos: 2,
    vbd: 18,
    vols: 9,
    fpVorp: 9,
    vbdRank: 131,
  },
  {
    id: "p171",
    name: "Jauan Jennings",
    pos: "WR",
    team: "MIN",
    bye: 6,
    projectedPoints: 264,
    consensusRank: 171,
    adp: 137.0,
    tier: 10,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 222,
  },
  {
    id: "p172",
    name: "Dontayvion Wicks",
    pos: "WR",
    team: "PHI",
    bye: 10,
    projectedPoints: 264,
    consensusRank: 172,
    adp: 87.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 265,
  },
  {
    id: "p173",
    name: "Omar Cooper Jr.",
    pos: "WR",
    team: "NYJ",
    bye: 13,
    projectedPoints: 264,
    consensusRank: 173,
    adp: 121.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 244,
  },
  {
    id: "p174",
    name: "Tre' Harris",
    pos: "WR",
    team: "LAC",
    bye: 7,
    projectedPoints: 263,
    consensusRank: 174,
    adp: 110.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 261,
  },
  {
    id: "p175",
    name: "Pat Bryant",
    pos: "WR",
    team: "DEN",
    bye: 10,
    projectedPoints: 262,
    consensusRank: 175,
    adp: 72.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 316,
  },
  {
    id: "p176",
    name: "Philadelphia Eagles",
    pos: "DST",
    team: "PHI",
    bye: 10,
    projectedPoints: 85,
    consensusRank: 176,
    adp: 213.0,
    tier: 10,
    sos: 0,
    vbd: 2,
    vols: 1,
    fpVorp: 1,
    vbdRank: 168,
  },
  {
    id: "p177",
    name: "Ryan Flournoy",
    pos: "WR",
    team: "DAL",
    bye: 14,
    projectedPoints: 262,
    consensusRank: 177,
    adp: 122.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 337,
  },
  {
    id: "p178",
    name: "T.J. Hockenson",
    pos: "TE",
    team: "MIN",
    bye: 6,
    projectedPoints: 261,
    consensusRank: 178,
    adp: 189.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 234,
  },
  {
    id: "p179",
    name: "Ray Davis",
    pos: "RB",
    team: "BUF",
    bye: 7,
    projectedPoints: 260,
    consensusRank: 179,
    adp: 129.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 312,
  },
  {
    id: "p180",
    name: "Malik Washington",
    pos: "WR",
    team: "MIA",
    bye: 6,
    projectedPoints: 260,
    consensusRank: 180,
    adp: 137.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 233,
  },
  {
    id: "p181",
    name: "Brandon Aubrey",
    pos: "K",
    team: "DAL",
    bye: 14,
    projectedPoints: 96,
    consensusRank: 181,
    adp: 267.0,
    tier: 10,
    sos: 2,
    vbd: 38,
    vols: 19,
    fpVorp: 19,
    vbdRank: 98,
  },
  {
    id: "p182",
    name: "Minnesota Vikings",
    pos: "DST",
    team: "MIN",
    bye: 6,
    projectedPoints: 80,
    consensusRank: 182,
    adp: 202.0,
    tier: 10,
    sos: 1,
    vbd: 22,
    vols: 11,
    fpVorp: 11,
    vbdRank: 124,
  },
  {
    id: "p183",
    name: "Pittsburgh Steelers",
    pos: "DST",
    team: "PIT",
    bye: 9,
    projectedPoints: 80,
    consensusRank: 183,
    adp: 215.0,
    tier: 10,
    sos: 5,
    vbd: 20,
    vols: 10,
    fpVorp: 10,
    vbdRank: 127,
  },
  {
    id: "p184",
    name: "Jalen Nailor",
    pos: "WR",
    team: "LV",
    bye: 13,
    projectedPoints: 258,
    consensusRank: 184,
    adp: 166.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 221,
  },
  {
    id: "p185",
    name: "New England Patriots",
    pos: "DST",
    team: "NE",
    bye: 11,
    projectedPoints: 78,
    consensusRank: 185,
    adp: 217.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 189,
  },
  {
    id: "p186",
    name: "Jacoby Brissett",
    pos: "QB",
    team: "ARI",
    bye: 14,
    projectedPoints: 257,
    consensusRank: 186,
    adp: 151.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 307,
  },
  {
    id: "p187",
    name: "Keenan Allen",
    pos: "WR",
    team: "IND",
    bye: 13,
    projectedPoints: 256,
    consensusRank: 187,
    adp: 211.0,
    tier: 10,
    sos: 4,
    vbd: 9,
    vols: 0,
    fpVorp: 9,
    vbdRank: 149,
  },
  {
    id: "p188",
    name: "Jacksonville Jaguars",
    pos: "DST",
    team: "JAC",
    bye: 7,
    projectedPoints: 76,
    consensusRank: 188,
    adp: 210.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 185,
  },
  {
    id: "p189",
    name: "Ka'imi Fairbairn",
    pos: "K",
    team: "HOU",
    bye: 8,
    projectedPoints: 90,
    consensusRank: 189,
    adp: 246.0,
    tier: 10,
    sos: 2,
    vbd: 26,
    vols: 13,
    fpVorp: 13,
    vbdRank: 119,
  },
  {
    id: "p190",
    name: "Isiah Pacheco",
    pos: "RB",
    team: "DET",
    bye: 6,
    projectedPoints: 255,
    consensusRank: 190,
    adp: 221.0,
    tier: 10,
    sos: 5,
    vbd: 15,
    vols: 0,
    fpVorp: 15,
    vbdRank: 136,
  },
  {
    id: "p191",
    name: "Cameron Dicker",
    pos: "K",
    team: "LAC",
    bye: 7,
    projectedPoints: 88,
    consensusRank: 191,
    adp: 249.0,
    tier: 10,
    sos: 2,
    vbd: 22,
    vols: 11,
    fpVorp: 11,
    vbdRank: 123,
  },
  {
    id: "p192",
    name: "Los Angeles Chargers",
    pos: "DST",
    team: "LAC",
    bye: 7,
    projectedPoints: 72,
    consensusRank: 192,
    adp: 213.0,
    tier: 10,
    sos: 3,
    vbd: 14,
    vols: 7,
    fpVorp: 7,
    vbdRank: 138,
  },
  {
    id: "p193",
    name: "Kimani Vidal",
    pos: "RB",
    team: "LAC",
    bye: 7,
    projectedPoints: 254,
    consensusRank: 193,
    adp: 144.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 252,
  },
  {
    id: "p194",
    name: "Baltimore Ravens",
    pos: "DST",
    team: "BAL",
    bye: 13,
    projectedPoints: 71,
    consensusRank: 194,
    adp: 233.0,
    tier: 10,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 176,
  },
  {
    id: "p195",
    name: "Terrance Ferguson",
    pos: "TE",
    team: "LAR",
    bye: 11,
    projectedPoints: 252,
    consensusRank: 195,
    adp: 191.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 274,
  },
  {
    id: "p196",
    name: "Travis Hunter",
    pos: "WR",
    team: "JAC",
    bye: 7,
    projectedPoints: 252,
    consensusRank: 196,
    adp: 173.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 250,
  },
  {
    id: "p197",
    name: "Jaylin Noel",
    pos: "WR",
    team: "HOU",
    bye: 8,
    projectedPoints: 252,
    consensusRank: 197,
    adp: 117.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 229,
  },
  {
    id: "p198",
    name: "AJ Barner",
    pos: "TE",
    team: "SEA",
    bye: 11,
    projectedPoints: 251,
    consensusRank: 198,
    adp: 187.0,
    tier: 10,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 285,
  },
  {
    id: "p199",
    name: "Jason Myers",
    pos: "K",
    team: "SEA",
    bye: 11,
    projectedPoints: 82,
    consensusRank: 199,
    adp: 262.0,
    tier: 10,
    sos: 4,
    vbd: 36,
    vols: 18,
    fpVorp: 18,
    vbdRank: 104,
  },
  {
    id: "p200",
    name: "Cam Little",
    pos: "K",
    team: "JAC",
    bye: 7,
    projectedPoints: 81,
    consensusRank: 200,
    adp: 250.0,
    tier: 10,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 173,
  },
  {
    id: "p201",
    name: "Calvin Ridley",
    pos: "WR",
    team: "TEN",
    bye: 9,
    projectedPoints: 250,
    consensusRank: 201,
    adp: 209.0,
    tier: 10,
    sos: 3,
    vbd: 11,
    vols: 0,
    fpVorp: 11,
    vbdRank: 141,
  },
  {
    id: "p202",
    name: "Aaron Rodgers",
    pos: "QB",
    team: "PIT",
    bye: 9,
    projectedPoints: 249,
    consensusRank: 202,
    adp: 168.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 339,
  },
  {
    id: "p203",
    name: "Sean Tucker",
    pos: "RB",
    team: "TB",
    bye: 10,
    projectedPoints: 248,
    consensusRank: 203,
    adp: 158.0,
    tier: 10,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 278,
  },
  {
    id: "p204",
    name: "Eddy Pineiro",
    pos: "K",
    team: "SF",
    bye: 8,
    projectedPoints: 80,
    consensusRank: 204,
    adp: 228.0,
    tier: 11,
    sos: 5,
    vbd: 2,
    vols: 1,
    fpVorp: 1,
    vbdRank: 167,
  },
  {
    id: "p205",
    name: "Ja'Kobi Lane",
    pos: "WR",
    team: "BAL",
    bye: 13,
    projectedPoints: 248,
    consensusRank: 205,
    adp: 234.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 272,
  },
  {
    id: "p206",
    name: "Gunnar Helm",
    pos: "TE",
    team: "TEN",
    bye: 9,
    projectedPoints: 247,
    consensusRank: 206,
    adp: 133.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 350,
  },
  {
    id: "p207",
    name: "Kansas City Chiefs",
    pos: "DST",
    team: "KC",
    bye: 5,
    projectedPoints: 60,
    consensusRank: 207,
    adp: 223.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 207,
  },
  {
    id: "p208",
    name: "Kenyon Sadiq",
    pos: "TE",
    team: "NYJ",
    bye: 13,
    projectedPoints: 246,
    consensusRank: 208,
    adp: 242.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 247,
  },
  {
    id: "p209",
    name: "Green Bay Packers",
    pos: "DST",
    team: "GB",
    bye: 11,
    projectedPoints: 60,
    consensusRank: 209,
    adp: 228.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 202,
  },
  {
    id: "p210",
    name: "Tyler Loop",
    pos: "K",
    team: "BAL",
    bye: 13,
    projectedPoints: 80,
    consensusRank: 210,
    adp: 238.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 174,
  },
  {
    id: "p211",
    name: "Nicholas Singleton",
    pos: "RB",
    team: "TEN",
    bye: 9,
    projectedPoints: 244,
    consensusRank: 211,
    adp: 183.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 318,
  },
  {
    id: "p212",
    name: "Geno Smith",
    pos: "QB",
    team: "NYJ",
    bye: 13,
    projectedPoints: 244,
    consensusRank: 212,
    adp: 42.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 336,
  },
  {
    id: "p213",
    name: "Kaelon Black",
    pos: "RB",
    team: "SF",
    bye: 8,
    projectedPoints: 244,
    consensusRank: 213,
    adp: 230.0,
    tier: 11,
    sos: 2,
    vbd: 9,
    vols: 0,
    fpVorp: 9,
    vbdRank: 150,
  },
  {
    id: "p214",
    name: "Oronde Gadsden II",
    pos: "TE",
    team: "LAC",
    bye: 7,
    projectedPoints: 243,
    consensusRank: 214,
    adp: 208.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 301,
  },
  {
    id: "p215",
    name: "Jake Bates",
    pos: "K",
    team: "DET",
    bye: 6,
    projectedPoints: 80,
    consensusRank: 215,
    adp: 270.0,
    tier: 11,
    sos: 5,
    vbd: 8,
    vols: 4,
    fpVorp: 4,
    vbdRank: 152,
  },
  {
    id: "p216",
    name: "Malachi Fields",
    pos: "WR",
    team: "NYG",
    bye: 8,
    projectedPoints: 242,
    consensusRank: 216,
    adp: 204.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 311,
  },
  {
    id: "p217",
    name: "Isaac TeSlaa",
    pos: "WR",
    team: "DET",
    bye: 6,
    projectedPoints: 242,
    consensusRank: 217,
    adp: 194.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 308,
  },
  {
    id: "p218",
    name: "Chris Bell",
    pos: "WR",
    team: "MIA",
    bye: 6,
    projectedPoints: 241,
    consensusRank: 218,
    adp: 191.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 242,
  },
  {
    id: "p219",
    name: "Rashod Bateman",
    pos: "WR",
    team: "BAL",
    bye: 13,
    projectedPoints: 240,
    consensusRank: 219,
    adp: 157.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 208,
  },
  {
    id: "p220",
    name: "James Conner",
    pos: "RB",
    team: "ARI",
    bye: 14,
    projectedPoints: 240,
    consensusRank: 220,
    adp: 167.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 249,
  },
  {
    id: "p221",
    name: "Cooper Kupp",
    pos: "WR",
    team: "SEA",
    bye: 11,
    projectedPoints: 240,
    consensusRank: 221,
    adp: 232.0,
    tier: 11,
    sos: 3,
    vbd: 10,
    vols: 0,
    fpVorp: 10,
    vbdRank: 147,
  },
  {
    id: "p222",
    name: "Cairo Santos",
    pos: "K",
    team: "CHI",
    bye: 10,
    projectedPoints: 80,
    consensusRank: 222,
    adp: 250.0,
    tier: 11,
    sos: 0,
    vbd: 2,
    vols: 1,
    fpVorp: 1,
    vbdRank: 165,
  },
  {
    id: "p223",
    name: "Zachariah Branch",
    pos: "WR",
    team: "ATL",
    bye: 11,
    projectedPoints: 238,
    consensusRank: 223,
    adp: 179.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 304,
  },
  {
    id: "p224",
    name: "Evan McPherson",
    pos: "K",
    team: "CIN",
    bye: 6,
    projectedPoints: 80,
    consensusRank: 224,
    adp: 262.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 188,
  },
  {
    id: "p225",
    name: "Pat Freiermuth",
    pos: "TE",
    team: "PIT",
    bye: 9,
    projectedPoints: 238,
    consensusRank: 225,
    adp: 204.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 246,
  },
  {
    id: "p226",
    name: "Darnell Mooney",
    pos: "WR",
    team: "NYG",
    bye: 8,
    projectedPoints: 237,
    consensusRank: 226,
    adp: 151.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 295,
  },
  {
    id: "p227",
    name: "Troy Franklin",
    pos: "WR",
    team: "DEN",
    bye: 10,
    projectedPoints: 236,
    consensusRank: 227,
    adp: 163.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 262,
  },
  {
    id: "p228",
    name: "Detroit Lions",
    pos: "DST",
    team: "DET",
    bye: 6,
    projectedPoints: 60,
    consensusRank: 228,
    adp: 273.0,
    tier: 11,
    sos: 5,
    vbd: 10,
    vols: 5,
    fpVorp: 5,
    vbdRank: 146,
  },
  {
    id: "p229",
    name: "Andy Borregales",
    pos: "K",
    team: "NE",
    bye: 11,
    projectedPoints: 80,
    consensusRank: 229,
    adp: 244.0,
    tier: 11,
    sos: 1,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 217,
  },
  {
    id: "p230",
    name: "Germie Bernard",
    pos: "WR",
    team: "PIT",
    bye: 9,
    projectedPoints: 235,
    consensusRank: 230,
    adp: 176.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 260,
  },
  {
    id: "p231",
    name: "Malik Davis",
    pos: "RB",
    team: "DAL",
    bye: 14,
    projectedPoints: 234,
    consensusRank: 231,
    adp: 194.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 245,
  },
  {
    id: "p232",
    name: "Caleb Douglas",
    pos: "WR",
    team: "MIA",
    bye: 6,
    projectedPoints: 234,
    consensusRank: 232,
    adp: 251.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 314,
  },
  {
    id: "p233",
    name: "Kaytron Allen",
    pos: "RB",
    team: "WAS",
    bye: 7,
    projectedPoints: 234,
    consensusRank: 233,
    adp: 217.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 320,
  },
  {
    id: "p234",
    name: "Harrison Mevis",
    pos: "K",
    team: "LAR",
    bye: 11,
    projectedPoints: 80,
    consensusRank: 234,
    adp: 304.0,
    tier: 11,
    sos: 2,
    vbd: 6,
    vols: 3,
    fpVorp: 3,
    vbdRank: 155,
  },
  {
    id: "p235",
    name: "Cade Otton",
    pos: "TE",
    team: "TB",
    bye: 10,
    projectedPoints: 232,
    consensusRank: 235,
    adp: 229.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 259,
  },
  {
    id: "p236",
    name: "Buffalo Bills",
    pos: "DST",
    team: "BUF",
    bye: 7,
    projectedPoints: 60,
    consensusRank: 236,
    adp: 283.0,
    tier: 11,
    sos: 3,
    vbd: 10,
    vols: 5,
    fpVorp: 5,
    vbdRank: 145,
  },
  {
    id: "p237",
    name: "Tank Dell",
    pos: "WR",
    team: "HOU",
    bye: 8,
    projectedPoints: 232,
    consensusRank: 237,
    adp: 270.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 382,
  },
  {
    id: "p238",
    name: "Justice Hill",
    pos: "RB",
    team: "BAL",
    bye: 13,
    projectedPoints: 231,
    consensusRank: 238,
    adp: 252.0,
    tier: 11,
    sos: 3,
    vbd: 10,
    vols: 0,
    fpVorp: 10,
    vbdRank: 148,
  },
  {
    id: "p239",
    name: "Chase McLaughlin",
    pos: "K",
    team: "TB",
    bye: 10,
    projectedPoints: 80,
    consensusRank: 239,
    adp: 261.0,
    tier: 11,
    sos: 3,
    vbd: 2,
    vols: 1,
    fpVorp: 1,
    vbdRank: 166,
  },
  {
    id: "p240",
    name: "Jaylen Wright",
    pos: "RB",
    team: "MIA",
    bye: 6,
    projectedPoints: 230,
    consensusRank: 240,
    adp: 225.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 239,
  },
  {
    id: "p241",
    name: "George Holani",
    pos: "RB",
    team: "SEA",
    bye: 11,
    projectedPoints: 230,
    consensusRank: 241,
    adp: 222.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 264,
  },
  {
    id: "p242",
    name: "Emanuel Wilson",
    pos: "RB",
    team: "SEA",
    bye: 11,
    projectedPoints: 229,
    consensusRank: 242,
    adp: 173.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 225,
  },
  {
    id: "p243",
    name: "Najee Harris",
    pos: "RB",
    team: "NYG",
    bye: 8,
    projectedPoints: 228,
    consensusRank: 243,
    adp: 249.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 197,
  },
  {
    id: "p244",
    name: "Cleveland Browns",
    pos: "DST",
    team: "CLE",
    bye: 11,
    projectedPoints: 60,
    consensusRank: 244,
    adp: 290.0,
    tier: 11,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 181,
  },
  {
    id: "p245",
    name: "Antonio Williams",
    pos: "WR",
    team: "WAS",
    bye: 7,
    projectedPoints: 228,
    consensusRank: 245,
    adp: 218.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 299,
  },
  {
    id: "p246",
    name: "Ted Hurst III",
    pos: "WR",
    team: "TB",
    bye: 10,
    projectedPoints: 227,
    consensusRank: 246,
    adp: 198.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 326,
  },
  {
    id: "p247",
    name: "Greg Dulcich",
    pos: "TE",
    team: "MIA",
    bye: 6,
    projectedPoints: 226,
    consensusRank: 247,
    adp: 278.0,
    tier: 11,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 238,
  },
  {
    id: "p248",
    name: "Devaughn Vele",
    pos: "WR",
    team: "NO",
    bye: 8,
    projectedPoints: 226,
    consensusRank: 248,
    adp: 243.0,
    tier: 11,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 258,
  },
  {
    id: "p249",
    name: "Chris Brooks",
    pos: "RB",
    team: "GB",
    bye: 11,
    projectedPoints: 226,
    consensusRank: 249,
    adp: 224.0,
    tier: 11,
    sos: 4,
    vbd: 4,
    vols: 0,
    fpVorp: 4,
    vbdRank: 162,
  },
  {
    id: "p250",
    name: "Keon Coleman",
    pos: "WR",
    team: "BUF",
    bye: 7,
    projectedPoints: 225,
    consensusRank: 250,
    adp: 204.0,
    tier: 11,
    sos: 4,
    injuryStatus: "Q",
    injuryDetails: "Foot",
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 360,
  },
  {
    id: "p251",
    name: "Evan Engram",
    pos: "TE",
    team: "DEN",
    bye: 10,
    projectedPoints: 224,
    consensusRank: 251,
    adp: 141.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 298,
  },
  {
    id: "p252",
    name: "Jack Bech",
    pos: "WR",
    team: "LV",
    bye: 13,
    projectedPoints: 224,
    consensusRank: 252,
    adp: 206.0,
    tier: 11,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 289,
  },
  {
    id: "p253",
    name: "Kaleb Johnson",
    pos: "RB",
    team: "GB",
    bye: 11,
    projectedPoints: 224,
    consensusRank: 253,
    adp: 288.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 347,
  },
  {
    id: "p254",
    name: "David Njoku",
    pos: "TE",
    team: "LAC",
    bye: 7,
    projectedPoints: 223,
    consensusRank: 254,
    adp: 293.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 325,
  },
  {
    id: "p255",
    name: "Harrison Butker",
    pos: "K",
    team: "KC",
    bye: 5,
    projectedPoints: 80,
    consensusRank: 255,
    adp: 333.0,
    tier: 11,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 175,
  },
  {
    id: "p256",
    name: "Chris Boswell",
    pos: "K",
    team: "PIT",
    bye: 9,
    projectedPoints: 80,
    consensusRank: 256,
    adp: 304.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 219,
  },
  {
    id: "p257",
    name: "Fernando Mendoza",
    pos: "QB",
    team: "LV",
    bye: 13,
    projectedPoints: 222,
    consensusRank: 257,
    adp: 287.0,
    tier: 11,
    sos: 1,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p258",
    name: "Demond Claiborne",
    pos: "RB",
    team: "MIN",
    bye: 6,
    projectedPoints: 221,
    consensusRank: 258,
    adp: 204.0,
    tier: 11,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 328,
  },
  {
    id: "p259",
    name: "Samaje Perine",
    pos: "RB",
    team: "CIN",
    bye: 6,
    projectedPoints: 220,
    consensusRank: 259,
    adp: 243.0,
    tier: 11,
    sos: 2,
    vbd: 6,
    vols: 0,
    fpVorp: 6,
    vbdRank: 159,
  },
  {
    id: "p260",
    name: "Chimere Dike",
    pos: "WR",
    team: "TEN",
    bye: 9,
    projectedPoints: 220,
    consensusRank: 260,
    adp: 257.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 310,
  },
  {
    id: "p261",
    name: "Elic Ayomanor",
    pos: "WR",
    team: "TEN",
    bye: 9,
    projectedPoints: 220,
    consensusRank: 261,
    adp: 207.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 280,
  },
  {
    id: "p262",
    name: "Ollie Gordon II",
    pos: "RB",
    team: "MIA",
    bye: 6,
    projectedPoints: 219,
    consensusRank: 262,
    adp: 107.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 303,
  },
  {
    id: "p263",
    name: "Isaiah Davis",
    pos: "RB",
    team: "NYJ",
    bye: 13,
    projectedPoints: 218,
    consensusRank: 263,
    adp: 1.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 270,
  },
  {
    id: "p264",
    name: "Cyrus Allen",
    pos: "WR",
    team: "KC",
    bye: 5,
    projectedPoints: 218,
    consensusRank: 264,
    adp: 325.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 384,
  },
  {
    id: "p265",
    name: "LeQuint Allen Jr.",
    pos: "RB",
    team: "JAC",
    bye: 7,
    projectedPoints: 218,
    consensusRank: 265,
    adp: 100.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 276,
  },
  {
    id: "p266",
    name: "Ty Johnson",
    pos: "RB",
    team: "BUF",
    bye: 7,
    projectedPoints: 217,
    consensusRank: 266,
    adp: 230.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 187,
  },
  {
    id: "p267",
    name: "Colby Parkinson",
    pos: "TE",
    team: "LAR",
    bye: 11,
    projectedPoints: 216,
    consensusRank: 267,
    adp: 224.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 359,
  },
  {
    id: "p268",
    name: "Tyquan Thornton",
    pos: "WR",
    team: "KC",
    bye: 5,
    projectedPoints: 216,
    consensusRank: 268,
    adp: 111.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 293,
  },
  {
    id: "p269",
    name: "Jordan James",
    pos: "RB",
    team: "SF",
    bye: 8,
    projectedPoints: 216,
    consensusRank: 269,
    adp: 308.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 203,
  },
  {
    id: "p270",
    name: "Seth McGowan",
    pos: "RB",
    team: "IND",
    bye: 13,
    projectedPoints: 215,
    consensusRank: 270,
    adp: 252.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 305,
  },
  {
    id: "p271",
    name: "Tory Horton",
    pos: "WR",
    team: "SEA",
    bye: 11,
    projectedPoints: 214,
    consensusRank: 271,
    adp: 245.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 321,
  },
  {
    id: "p272",
    name: "Will Reichard",
    pos: "K",
    team: "MIN",
    bye: 6,
    projectedPoints: 80,
    consensusRank: 272,
    adp: 356.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 180,
  },
  {
    id: "p273",
    name: "Wil Lutz",
    pos: "K",
    team: "DEN",
    bye: 10,
    projectedPoints: 80,
    consensusRank: 273,
    adp: 339.0,
    tier: 12,
    sos: 1,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 191,
  },
  {
    id: "p274",
    name: "Elijah Sarratt",
    pos: "WR",
    team: "BAL",
    bye: 13,
    projectedPoints: 213,
    consensusRank: 274,
    adp: 199.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p275",
    name: "Tua Tagovailoa",
    pos: "QB",
    team: "ATL",
    bye: 11,
    projectedPoints: 212,
    consensusRank: 275,
    adp: 265.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p276",
    name: "Michael Penix Jr.",
    pos: "QB",
    team: "ATL",
    bye: 11,
    projectedPoints: 212,
    consensusRank: 276,
    adp: 270.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p277",
    name: "Darius Slayton",
    pos: "WR",
    team: "NYG",
    bye: 8,
    projectedPoints: 212,
    consensusRank: 277,
    adp: 59.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 296,
  },
  {
    id: "p278",
    name: "Xavier Legette",
    pos: "WR",
    team: "CAR",
    bye: 5,
    projectedPoints: 211,
    consensusRank: 278,
    adp: 51.0,
    tier: 12,
    sos: 2,
    injuryStatus: "Q",
    injuryDetails: "Ankle",
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 277,
  },
  {
    id: "p279",
    name: "Mason Taylor",
    pos: "TE",
    team: "NYJ",
    bye: 13,
    projectedPoints: 210,
    consensusRank: 279,
    adp: 271.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 364,
  },
  {
    id: "p280",
    name: "Marvin Mims Jr.",
    pos: "WR",
    team: "DEN",
    bye: 10,
    projectedPoints: 210,
    consensusRank: 280,
    adp: 261.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 286,
  },
  {
    id: "p281",
    name: "Christian Kirk",
    pos: "WR",
    team: "SF",
    bye: 8,
    projectedPoints: 210,
    consensusRank: 281,
    adp: 304.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 317,
  },
  {
    id: "p282",
    name: "Kirk Cousins",
    pos: "QB",
    team: "LV",
    bye: 13,
    projectedPoints: 209,
    consensusRank: 282,
    adp: 264.0,
    tier: 12,
    sos: 1,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p283",
    name: "Kendre Miller",
    pos: "RB",
    team: "NO",
    bye: 8,
    projectedPoints: 208,
    consensusRank: 283,
    adp: 242.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 332,
  },
  {
    id: "p284",
    name: "DJ Giddens",
    pos: "RB",
    team: "IND",
    bye: 13,
    projectedPoints: 208,
    consensusRank: 284,
    adp: 133.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 288,
  },
  {
    id: "p285",
    name: "Deshaun Watson",
    pos: "QB",
    team: "CLE",
    bye: 11,
    projectedPoints: 208,
    consensusRank: 285,
    adp: 168.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p286",
    name: "Theo Johnson",
    pos: "TE",
    team: "NYG",
    bye: 8,
    projectedPoints: 207,
    consensusRank: 286,
    adp: 247.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 395,
  },
  {
    id: "p287",
    name: "Shedeur Sanders",
    pos: "QB",
    team: "CLE",
    bye: 11,
    projectedPoints: 206,
    consensusRank: 287,
    adp: 322.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p288",
    name: "Kyle Williams",
    pos: "WR",
    team: "NE",
    bye: 11,
    projectedPoints: 206,
    consensusRank: 288,
    adp: 315.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p289",
    name: "Brashard Smith",
    pos: "RB",
    team: "KC",
    bye: 5,
    projectedPoints: 206,
    consensusRank: 289,
    adp: 237.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 254,
  },
  {
    id: "p290",
    name: "San Francisco 49ers",
    pos: "DST",
    team: "SF",
    bye: 8,
    projectedPoints: 60,
    consensusRank: 290,
    adp: 347.0,
    tier: 12,
    sos: 3,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 220,
  },
  {
    id: "p291",
    name: "Devin Singletary",
    pos: "RB",
    team: "NYG",
    bye: 8,
    projectedPoints: 204,
    consensusRank: 291,
    adp: 320.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 294,
  },
  {
    id: "p292",
    name: "New Orleans Saints",
    pos: "DST",
    team: "NO",
    bye: 8,
    projectedPoints: 60,
    consensusRank: 292,
    adp: 334.0,
    tier: 12,
    sos: 5,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 186,
  },
  {
    id: "p293",
    name: "Eli Stowers",
    pos: "TE",
    team: "PHI",
    bye: 10,
    projectedPoints: 204,
    consensusRank: 293,
    adp: 327.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p294",
    name: "Atlanta Falcons",
    pos: "DST",
    team: "ATL",
    bye: 11,
    projectedPoints: 60,
    consensusRank: 294,
    adp: 354.0,
    tier: 12,
    sos: 4,
    vbd: 6,
    vols: 3,
    fpVorp: 3,
    vbdRank: 157,
  },
  {
    id: "p295",
    name: "Mack Hollins",
    pos: "WR",
    team: "NE",
    bye: 11,
    projectedPoints: 202,
    consensusRank: 295,
    adp: 1.0,
    tier: 12,
    sos: 2,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 365,
  },
  {
    id: "p296",
    name: "Skyler Bell",
    pos: "WR",
    team: "BUF",
    bye: 7,
    projectedPoints: 202,
    consensusRank: 296,
    adp: 275.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p297",
    name: "Jaydon Blue",
    pos: "RB",
    team: "PHI",
    bye: 10,
    projectedPoints: 202,
    consensusRank: 297,
    adp: 323.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
  },
  {
    id: "p298",
    name: "Hollywood Brown",
    pos: "WR",
    team: "PHI",
    bye: 10,
    projectedPoints: 201,
    consensusRank: 298,
    adp: 260.0,
    tier: 12,
    sos: 4,
    injuryStatus: "Q",
    injuryDetails: "Shoulder",
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 322,
  },
  {
    id: "p299",
    name: "Adam Randall",
    pos: "RB",
    team: "BAL",
    bye: 13,
    projectedPoints: 200,
    consensusRank: 299,
    adp: 1.0,
    tier: 12,
    sos: 3,
    injuryStatus: "IR",
    injuryDetails: "Undisclosed",
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 275,
  },
  {
    id: "p300",
    name: "Emari Demercado",
    pos: "RB",
    team: "DAL",
    bye: 14,
    projectedPoints: 200,
    consensusRank: 300,
    adp: 222.0,
    tier: 12,
    sos: 4,
    vbd: 0,
    vols: 0,
    fpVorp: 0,
    vbdRank: 306,
  },
];
